### ISSUE TITLE
Quantile error bounds

### ISSUE THREAD

**Issue by hpx7** [DataSketches/sketches-core#133]
Is it possible to get upper/lower bounds for quantile results? E.g. I'd like to know that the median is 5.0 +/- 0.05 with 95% confidence.

There seem to be comments that mention that the normalized rank error can't directly be applied to determine these bounds, but surely there must be some way to bound the error here?

**Comment by leerho** [comment]
The error of the quantile algorithms is not relative error as it is with Theta Sketches.  It is an absolute error that only relates to the normalized rank and NOT the value determined from the rank (e.g. the median).   Without prior knowledge of the underlying distribution of values, it is NOT possible to predict forward error bounds on the values (quantiles) with a sub-linear algorithm.   It is important to realize that the quantiles algorithm in the library is **distribution independent**, which many other quantile algorithms are clearly not.

As explained in the (slightly corrected) javadocs for `DoublesSketch`: 

> For example, choosing a K of 256 yields a normalized rank error of less than 1%. The upper bound on the median value obtained by getQuantile(0.5) would be the value in the hypothetical ordered stream of values at the normalized rank of 0.51.  The lower bound would be the value in the hypothetical ordered stream of values at the normalized rank of 0.49.

So what you can do is the following, after-the-fact, after the sketch is loaded with data:

```
double median = sketch.getQuantile(0.5);
double error = getNormalizedRankError();
double upperBoundValue = sketch.getQuantile(min(0.5 + error, 1.0));
double lowerBoundValue = sketch.getQuantile(max(0.5 - error, 0.0));
```

There is high confidence that the true median is within those bounds. The error distribution is not Gaussian as it is (approximately) with Theta Sketches, so specifying standard error confidence bounds is impossible because, again, the underlying distribution is unknown.  Even the above code is approximate, as the true guarantee relates to UB and LB values computed against the hypothetical total stream of values and not just the sketch.

**Comment by hpx7** [comment]
I'm starting to appreciate why not knowing about the underlying distribution makes this challenging; however, I feel like I'm still missing something here. Judging from the other sketches in this repository, you guys certainly understand the value of bounding errors. Indeed, if you don't have a framework for talking about the errors in your estimates, then it becomes hard to justify your estimated values as being any better than random.

Perhaps it's a question of the api. If there was a method `getRank(item)`, would the normalized error rank apply to this estimate? Is it possible to support such a method with this sketch?

**Comment by AlexanderSaydakov** [comment]
> Perhaps it's a question of the api. If there was a method getRank(item), would the normalized error rank apply to this estimate? Is it possible to support such a method with this sketch?

There is no getRank(item) method, but there is getCDF(splitPoints) instead. You can call it with one split point. It will return an array of two values p1 and p2, where p1+p2=1. p1 is an estimate of the probability mass of the distribution of values less then the given split point. So p1 must be the best estimate of the rank of this item within getNormalizedRankError()

**Comment by leerho** [comment]
@hpx7 

> Indeed, if you don't have a framework for talking about the errors in your estimates, then it becomes hard to justify your estimated values as being any better than random.

We agree, and this is why for each sketch type in the library we carefully define how "error" is defined and its limitations.  All the sketches have some means of estimating the error of your results, and our error estimation algorithms are backed by rigorous mathematical proofs.

Now, the error definitions we provide may not be how you would like the error to be defined, but this is not an oversight.   We are providing you the best error estimates reasonably possible given the limits of these sub-linear, streaming algorithms and the known mathematics that supports them.  

I have given you a code snippet of how to get some idea of your error bounds for quantile values. We don't have a method `getQuantileError()` because it can be proven to fail dramatically given pathological distributions.  We do give you getNormalizedRankError() because we can prove that it works for all distributions.  That is the state of the art right now for this kind of sketch.  

> Perhaps it's a question of the api. If there was a method getRank(item), would the normalized error rank apply to this estimate? Is it possible to support such a method with this sketch?

Alex already responded to this, but there is a typo in his response,  he meant to recommend getPMF(splitpoints) with one splitpoint value, `v`.

**Comment by AlexanderSaydakov** [comment]
> Alex already responded to this, but there is a typo in his response, he meant to recommend getPMF(splitpoints) with one splitpoint value, v.

Yes, there is an inconsistency in my explanation. First I was thinking about getPMF, and, therefore, wrote that p1+p2=1. Then I thought about the case of getting ranks of several items, for which getCDF will be more convenient, so I changed getPMF to getCDF, but forgot to update the p1+p2=1 equation, which is no longer true. In case of calling getCDF() p2=1, but p1 is the same as from getPMF(). So in this case of calling them with one split point and only using p1, there is no difference. But if ranks of several items are desired, getCDF() provides all the ranks at once (plus one extra value at the end of the array with is always 1)

**Comment by hpx7** [comment]
Appreciate the responses.

So you could implement `getRank(item)` as follows:
```
getRank(item) = getPMF([item])[0]
```

One could imagine some sort of search algorithm that keeps calling this method on various inputs until it achieves the desired rank as output. This sort of offloads the knowledge of the distribution to the client making these calls. But I suppose there could be multiple items that e.g. all give back 0.5 as the rank and you wouldn't know which to pick. I guess what you're trying to tell me anyway is that error bounds on quantile values are simply not achievable (although I'm not sure if that's a limitation of this sketch in particular or with any sublinear sketch in general).

Given this `getRank(item)` method, I wonder what the contract of `getQuantile(getRank(item))` is. Would it always return `item`?

**Comment by AlexanderSaydakov** [comment]
> Given this getRank(item) method, I wonder what the contract of getQuantile(getRank(item)) is. Would it always return item?

No. First, you can call getRank() with an item, which was never presented to the sketch, and still get an approximate rank. Second, even if the sketch has seen this item, the item might not be retained as a part of the sketch, which is almost the same as the first case. Third, even if the item is retained in the sketch, you might get a different item (slightly less or slightly greater) due to the error in the rank.

**Comment by jmalkin** [comment]
Yes, multiple inputs may return the same rank.

And @AlexanderSaydakov already answered for the last question, but it's also in the very, very last paragraph of the (kind of long) Quantiles Sketch documentation, wehre it talks about "minor directional inconsistencies": [https://datasketches.github.io/docs/Quantiles/QuantilesOverview.html](https://datasketches.github.io/docs/Quantiles/QuantilesOverview.html)

**Comment by AlexanderSaydakov** [comment]
> I guess what you're trying to tell me anyway is that error bounds on quantile values are simply not achievable (although I'm not sure if that's a limitation of this sketch in particular or with any sublinear sketch in general).

Yes, error bounds on values are not achievable in a general case. And that is not a limitation of this particular sketch, but any approximation of quantiles.
