### ISSUE TITLE
Set Operations should support implied hash seeds

### ISSUE THREAD

**Issue by will-lauer** [DataSketches/sketches-core#33]
Currently, all the set operations enforce that incoming sketches have a specified hash seed. If no hash seed is specified, the default hash seed is implied. As an option, these operations should be able to infer the hash seed from the first sketch seen, allowing the operations to be used with non-standard seeds without having to specify the seed (a secret) up front. This has the effect of moving a possible error (mismatched seeds) later in the processing and possibly hiding the error all together if only a single sketch is seen, but has the advantage that users of the set operations don't have to know what their seeds are.

**Comment by leerho** [comment]
What you are requesting cannot be done safely.

The currently implemented seed "policy" is IF you decide to use a seed **different** from the default, you MUST specify the seed everywhere, for new sketches and for all set operations.  If you wish to share your unique-seed-created sketches with other organizations, AND if they need to perform set-ops, or build their own sketches to merge with your supplied data, then you must provide them with the seed through a separate secure channel.  For security reasons, your unique-seed should not be visible in the source code nor be stored along with the sketch data.   

The current sketches use a binary image Serialization-Version 3.  SerVer 3 sketches keep a 16-bit seed-hash of the chosen seed to provide a safety-check mechanism to catch the situation where a user accidentally tries to perform set operations from sketches generated with different seeds, which would otherwise silently generate garbage.  If you have old SerVer 1 sketch data (prior to Open Source and prior to the decision to allow specification of non-default seeds), then those sketch images (if generated with the correct seed), must be re-imaged using the current SerVer 3. 
This allows the safety-check mechanism to work.  This re-imaging of the old sketch data does not require access to the original data. It is just updating the sketch image to include the correct seed-hash.  The size will be the same, or in some cases, slightly smaller.

Two decisions were made to improve performance as well as improve robustness:

The Union API supports datum updates as well as sketch updates. This provides significant performance improvements especially in a real-time environments by eliminating the need for separate Update Sketches, where they would be immediately merged anyway.  The union operation cannot perform datum updates without full knowledge of what seed to use. It is NOT a good idea to just tell users they can't use the datum updates if it requires a non-default seed and they don't have the seed in hand, even if it is documented carefully.  This is because they might also have old SerVer1 sketch data that needs to be re-imaged as well.  Not forcing the users to provide the non-default seed would result in silent failures that would be difficult to debug. 

All the Set Operations ultimately require knowledge of what seed to use because of another requirement to never return nulls.  If a virgin Set Operation is created (Union, Intersection, or AnotB), and then followed immediately by a getResult(), the current policy is to always return an Empty Sketch (only 8 bytes). If the user wishes to replace these 8 byte images with null, it is their decision.   Nonetheless, this Empty Sketch has the seed-hash embedded in it as it is a valid sketch.

The continued presence of old SerVer1 sketch data presents a problem.  I propose a much simpler fix and that would be to provide a user updatable v1defaultUpdateSeed in the Util class.  When a V1 sketch is detected this is the seed that would be used for those sketches.   All the above still applies.

Lee.

**Comment by leerho** [comment]
Please ignore my last paragraph.  I decided the v1defaultUpdateSeed was not a good idea.

**Comment by leerho** [comment]
Supporting the old SerVer 1 sketch images will at some point be deprecated and no longer supported.  I encourage those groups that still have history in these sketches to convert them to SerVer 3.  For each v1 image you basically do the following:

byte[] v1ByteArray = <from disk or where ever>
Memory mem = NativeMemory(v1ByteArray);
CompactSketch sk = Sketch.heapify(mem, <Your long Seed >);
byte[] V3ByteArray = sk.toByteArray();
