### ISSUE TITLE
BigDecimal Theta Sketch

### ISSUE THREAD

**Issue by jleach4** [DataSketches/sketches-core#90]
How would one implement a theta Sketch for a BigDecimal?

**Comment by AlexanderSaydakov** [comment]
Just convert it to a format suitable for one of the update() methods of the theta sketch.
I would suggest something like sketch.update(bigDecimal.toString());

**Comment by AlexanderSaydakov** [comment]
Perhaps sketch.update(bigDecimal.toString().toCharArray()) is a bit faster since it avoids the complexity of the UTF8 encoding. But whatever method you choose - be consistent with it. These two methods I suggested will produce different hash keys in the sketches, so it won't be possible to do set operations with sketches built in different ways.
